/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.utils.MaterialBorders;
import mdlaf.utils.MaterialColors;
import utils.HintTextField;
import utils.RoundedButton;


public class FormCategoryToolView extends javax.swing.JPanel {

    /**
     * Creates new form ChatView
     */
    public FormCategoryToolView() {
        initComponents();
        MaterialUIMovement.add(actionForm, MaterialColors.BLUE_400);
        actionForm.setForeground(Color.white);
        
        MaterialUIMovement.add(actionDeleteClient, MaterialColors.RED_400);
        actionDeleteClient.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        chatContent = new javax.swing.JPanel();
        actionsContainer = new javax.swing.JPanel();
        backAction = new javax.swing.JButton();
        listContainer = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        descFiled = new javax.swing.JTextField();
        actionDeleteClient = new RoundedButton("ELIMINAR", MaterialColors.RED_400);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        actionForm = new RoundedButton("GUARDAR", MaterialColors.BLUE_400);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(864, 800));
        setPreferredSize(new java.awt.Dimension(780, 800));

        mainContainer.setBackground(new java.awt.Color(255, 255, 255));
        mainContainer.setPreferredSize(new java.awt.Dimension(780, 800));
        mainContainer.setRequestFocusEnabled(false);

        chatContent.setBackground(new java.awt.Color(255, 255, 255));
        chatContent.setPreferredSize(new java.awt.Dimension(780, 800));

        actionsContainer.setBackground(new java.awt.Color(255, 255, 255));
        actionsContainer.setPreferredSize(new java.awt.Dimension(780, 100));

        backAction.setText("REGRESAR");

        javax.swing.GroupLayout actionsContainerLayout = new javax.swing.GroupLayout(actionsContainer);
        actionsContainer.setLayout(actionsContainerLayout);
        actionsContainerLayout.setHorizontalGroup(
            actionsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionsContainerLayout.createSequentialGroup()
                .addContainerGap(616, Short.MAX_VALUE)
                .addComponent(backAction, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        actionsContainerLayout.setVerticalGroup(
            actionsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsContainerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(backAction, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        chatContent.add(actionsContainer);

        listContainer.setBackground(new java.awt.Color(255, 255, 255));
        listContainer.setPreferredSize(new java.awt.Dimension(864, 690));

        nameField.setSelectedTextColor(new java.awt.Color(38, 117, 191));

        jLabel1.setText("NOMBRE");

        jLabel2.setText("Descripción");

        javax.swing.GroupLayout listContainerLayout = new javax.swing.GroupLayout(listContainer);
        listContainer.setLayout(listContainerLayout);
        listContainerLayout.setHorizontalGroup(
            listContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listContainerLayout.createSequentialGroup()
                .addGroup(listContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listContainerLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(listContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(listContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(listContainerLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(listContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(actionDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actionForm, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        listContainerLayout.setVerticalGroup(
            listContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listContainerLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(listContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(actionForm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(actionDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        actionDeleteClient.getAccessibleContext().setAccessibleParent(actionDeleteClient);
        actionForm.getAccessibleContext().setAccessibleParent(actionForm);

        chatContent.add(listContainer);

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addComponent(chatContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actionDeleteClient;
    public javax.swing.JButton actionForm;
    private javax.swing.JPanel actionsContainer;
    public javax.swing.JButton backAction;
    public javax.swing.JPanel chatContent;
    public javax.swing.JTextField descFiled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel listContainer;
    public javax.swing.JPanel mainContainer;
    public javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
