/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import utils.Constants;
import utils.ImageRounded;


public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        lblImage.setIcon(new ImageRounded().loadImage("src/images/logo.png", 85));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        homeAction = new javax.swing.JButton();
        usersAction = new javax.swing.JButton();
        clientsAction = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        brandsAction = new javax.swing.JButton();
        categoriesAction = new javax.swing.JButton();
        servicesAction = new javax.swing.JButton();
        toolsAction = new javax.swing.JButton();
        productsAction = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        containerMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 800));
        setMinimumSize(new java.awt.Dimension(1000, 800));

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel2.setBackground(new java.awt.Color(93, 130, 253));

        homeAction.setBackground(new java.awt.Color(93, 130, 253));
        homeAction.setForeground(new java.awt.Color(255, 255, 255));
        homeAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeAction.setText("INICIO");
        homeAction.setBorder(null);
        homeAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionActionPerformed(evt);
            }
        });

        usersAction.setBackground(new java.awt.Color(93, 130, 253));
        usersAction.setForeground(new java.awt.Color(255, 255, 255));
        usersAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        usersAction.setText("USUARIOS");
        usersAction.setBorder(null);
        usersAction.setIconTextGap(5);

        clientsAction.setBackground(new java.awt.Color(93, 130, 253));
        clientsAction.setForeground(new java.awt.Color(255, 255, 255));
        clientsAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clients.png"))); // NOI18N
        clientsAction.setText("CLIENTES");
        clientsAction.setBorder(null);

        btnExit.setBackground(new java.awt.Color(93, 130, 253));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");

        brandsAction.setBackground(new java.awt.Color(93, 130, 253));
        brandsAction.setForeground(new java.awt.Color(255, 255, 255));
        brandsAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brands.png"))); // NOI18N
        brandsAction.setText("MARCAS");
        brandsAction.setBorder(null);
        brandsAction.setIconTextGap(5);

        categoriesAction.setBackground(new java.awt.Color(93, 130, 253));
        categoriesAction.setForeground(new java.awt.Color(255, 255, 255));
        categoriesAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aplicacion.png"))); // NOI18N
        categoriesAction.setText("CATEGORIAS");
        categoriesAction.setBorder(null);
        categoriesAction.setIconTextGap(5);

        servicesAction.setBackground(new java.awt.Color(93, 130, 253));
        servicesAction.setForeground(new java.awt.Color(255, 255, 255));
        servicesAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/services.png"))); // NOI18N
        servicesAction.setText("SERVICIOS");
        servicesAction.setBorder(null);
        servicesAction.setIconTextGap(5);

        toolsAction.setBackground(new java.awt.Color(93, 130, 253));
        toolsAction.setForeground(new java.awt.Color(255, 255, 255));
        toolsAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tools.png"))); // NOI18N
        toolsAction.setText("HERRAMIENTAS");
        toolsAction.setBorder(null);
        toolsAction.setIconTextGap(5);

        productsAction.setBackground(new java.awt.Color(93, 130, 253));
        productsAction.setForeground(new java.awt.Color(255, 255, 255));
        productsAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/products.png"))); // NOI18N
        productsAction.setText("PRODUCTOS");
        productsAction.setBorder(null);
        productsAction.setIconTextGap(5);

        lblImage.setBackground(new java.awt.Color(93, 130, 253));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientsAction)
                            .addComponent(homeAction)
                            .addComponent(usersAction)
                            .addComponent(brandsAction)
                            .addComponent(categoriesAction)
                            .addComponent(servicesAction))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productsAction)
                    .addComponent(toolsAction))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(homeAction)
                .addGap(18, 18, 18)
                .addComponent(clientsAction)
                .addGap(18, 18, 18)
                .addComponent(usersAction)
                .addGap(18, 18, 18)
                .addComponent(brandsAction)
                .addGap(18, 18, 18)
                .addComponent(categoriesAction)
                .addGap(18, 18, 18)
                .addComponent(servicesAction)
                .addGap(18, 18, 18)
                .addComponent(toolsAction)
                .addGap(18, 18, 18)
                .addComponent(productsAction)
                .addGap(88, 88, 88)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        containerMain.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout containerMainLayout = new javax.swing.GroupLayout(containerMain);
        containerMain.setLayout(containerMainLayout);
        containerMainLayout.setHorizontalGroup(
            containerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        containerMainLayout.setVerticalGroup(
            containerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(containerMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton brandsAction;
    public javax.swing.JButton btnExit;
    public javax.swing.JButton categoriesAction;
    public javax.swing.JButton clientsAction;
    public javax.swing.JPanel containerMain;
    public javax.swing.JButton homeAction;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblImage;
    public javax.swing.JButton productsAction;
    public javax.swing.JButton servicesAction;
    public javax.swing.JButton toolsAction;
    public javax.swing.JButton usersAction;
    // End of variables declaration//GEN-END:variables
}
